appstore/nextcloudappstore/urls.py
"""
SPDX-FileCopyrightText: 2016 Nextcloud GmbH and Nextcloud contributors
SPDX-License-Identifier: AGPL-3.0-or-later
"""

from allauth.account.views import signup
from allauth.socialaccount.views import signup as social_signup
from csp.decorators import csp_update
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import include, path, re_path
from django.views.decorators.http import etag

from nextcloudappstore.core.caching import app_rating_etag
from nextcloudappstore.core.feeds import AppReleaseAtomFeed, AppReleaseRssFeed
from nextcloudappstore.core.views import (
    AppDetailView,
    AppRatingApi,
    AppRegisterView,
    AppReleasesView,
    AppUploadView,
    CategoryAppListView,
    app_description,
)
from nextcloudappstore.scaffolding.views import (
    AppScaffoldingView,
    IntegrationScaffoldingView,
)

admin.site.login = login_required(admin.site.login)

urlpatterns = [
    path("", CategoryAppListView.as_view(), {"id": None}, name="home"),
    path("featured", CategoryAppListView.as_view(), {"id": None, "is_featured_category": True}, name="featured"),
    path("signup/", csp_update(**settings.CSP_SIGNUP)(signup), name="account_signup"),
    path("social/signup/", csp_update(**settings.CSP_SIGNUP)(social_signup), name="socialaccount_signup"),
    path("", include("allauth.urls")),
    re_path(r"^categories/(?P<id>[\w]*)/?$", CategoryAppListView.as_view(), name="category-app-list"),
    re_path(r"^developer/apps/generate/?$", AppScaffoldingView.as_view(), name="app-scaffold"),
    re_path(r"^developer/integration/new/?$", IntegrationScaffoldingView.as_view(), name="integration-scaffold"),
    re_path(r"^developer/apps/releases/new/?$", AppUploadView.as_view(), name="app-upload"),
    re_path(r"^developer/apps/new/?$", AppRegisterView.as_view(), name="app-register"),
    re_path(r"^apps/(?P<id>[\w_]+)/?$", AppDetailView.as_view(), name="app-detail"),
    re_path(r"^apps/(?P<id>[\w_]+)/releases/?$", AppReleasesView.as_view(), name="app-releases"),
    re_path(r"^apps/(?P<id>[\w_]+)/description/?$", app_description, name="app-description"),
    re_path(r"^apps/(?P<id>[\w_]+)/ratings.json$", etag(app_rating_etag)(AppRatingApi.as_view()), name="app-ratings"),
    path("api/", include("nextcloudappstore.api.urls", namespace="api")),
    path("account/", include("nextcloudappstore.user.urls", namespace="user")),
    re_path(r"^admin/", admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
    path("captcha/", include("captcha.urls")),
]

urlpatterns += i18n_patterns(
    re_path(r"feeds/releases.rss", AppReleaseRssFeed(), name="feeds-releases-rss"),
    re_path(r"feeds/releases.atom", AppReleaseAtomFeed(), name="feeds-releases-atom"),
)

if settings.DEBUG:
    try:
        import debug_toolbar

        urlpatterns += [
            path("__debug__/", include(debug_toolbar.urls)),
        ]
    except ImportError:
        pass

appstore/nextcloudappstore/user/urls.py
"""
SPDX-FileCopyrightText: 2017 Nextcloud GmbH and Nextcloud contributors
SPDX-License-Identifier: AGPL-3.0-or-later
"""

from django.urls import path, re_path

from nextcloudappstore.scaffolding.views import IntegrationScaffoldingView
from nextcloudappstore.user.views import (
    AccountView,
    APITokenView,
    AppealCommentsView,
    ChangeLanguageView,
    DeleteAccountView,
    EnterpriseAppsView,
    IntegrationsView,
    PasswordView,
    TransferAppsView,
)

app_name = "user"

urlpatterns = [
    path("", AccountView.as_view(), name="account"),
    re_path(r"^integrations/?$", IntegrationsView.as_view(), name="account-integrations"),
    re_path(r"^integrations/(?P<pk>[a-z0-9_]+)/?$", IntegrationScaffoldingView.as_view(), name="account-integration"),
    re_path(
        r"^integrations/(?P<pk>[a-z0-9_]+)/moderate/?$",
        IntegrationScaffoldingView.as_view(),
        name="account-integration-moderate",
    ),
    re_path(r"^transfer-apps/?$", TransferAppsView.as_view(), name="account-transfer-apps"),
    re_path(r"^transfer-apps/(?P<pk>[a-z0-9_]+)/?$", TransferAppsView.as_view(), name="account-transfer-app"),
    re_path(r"^orphan-apps/(?P<pk>[a-z0-9_]+)/?$", TransferAppsView.as_view(), name="account-orphan-app"),
    re_path(r"^enterprise-apps/?$", EnterpriseAppsView.as_view(), name="account-enterprise-apps"),
    re_path(r"^enterprise-apps/(?P<pk>[a-z0-9_]+)/?$", EnterpriseAppsView.as_view(), name="account-enterprise-app"),
    re_path(r"^password/?$", PasswordView.as_view(), name="account-password"),
    re_path(r"^token/?$", APITokenView.as_view(), name="account-api-token"),
    re_path(r"^delete/?$", DeleteAccountView.as_view(), name="account-deletion"),
    re_path(r"^change-language/?$", ChangeLanguageView.as_view(), name="account-change-language"),
    re_path(r"^appeal-comments/?$", AppealCommentsView.as_view(), name="appeal-comments"),
]

appstore/nextcloudappstore/user/models.py
"""
SPDX-FileCopyrightText: 2017 Nextcloud GmbH and Nextcloud contributors
SPDX-License-Identifier: AGPL-3.0-or-later
"""

from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver

from .odoo import subscribe_user_to_news, unsubscribe_user_from_news


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    subscribe_to_news = models.BooleanField(
        default=False, help_text="User has opted in to receive Nextcloud news and updates."
    )

    def __str__(self):
        return f"Profile of {self.user.username}"


# Signal to create a profile for each new user
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        profile = UserProfile.objects.create(user=instance)
        profile._skip_subscription_check = True  # Dynamically add the flag
        profile.save()


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


# Detect changes to subscribe_to_news and trigger actions
@receiver(pre_save, sender=UserProfile)
def handle_subscription_change(sender, instance, **kwargs):
    if hasattr(instance, "_skip_subscription_check") and instance._skip_subscription_check:
        return

    if instance.pk:  # Ensure this is an update, not a creation
        # Fetch the old value of subscribe_to_news
        old_value = UserProfile.objects.filter(pk=instance.pk).values_list("subscribe_to_news", flat=True).first()
        new_value = instance.subscribe_to_news

        if old_value != new_value:
            if new_value:
                # Logic to subscribe the user
                subscribe_user_to_news(instance.user.email, "")
            else:
                # Logic to unsubscribe the user
                unsubscribe_user_from_news(instance.user.email)

appstore/nextcloudappstore/user/views.py
"""
SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
SPDX-License-Identifier: AGPL-3.0-or-later
"""

from allauth.account.models import EmailAddress
from allauth.account.views import PasswordChangeView
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.generic import TemplateView, UpdateView

from nextcloudappstore.core.models import App, AppRating
from nextcloudappstore.user.forms import AccountForm, DeleteAccountForm


@method_decorator(never_cache, name="dispatch")
class IntegrationsView(LoginRequiredMixin, TemplateView):
    template_name = "user/integrations.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["apps"] = App.objects.filter(owner=self.request.user).filter(Q(is_integration=True) & Q(approved=True))
        if self.request.user.is_superuser:
            context["pending"] = App.objects.filter(is_integration=True).filter(approved=False)
        context["acc_page"] = "account-integrations"
        return context


@method_decorator(never_cache, name="dispatch")
class TransferAppsView(LoginRequiredMixin, TemplateView):
    template_name = "user/transfer-apps.html"

    def post(self, request, pk):
        app = get_object_or_404(App, pk=pk, owner=self.request.user)
        if "transfer" in request.path:
            app.ownership_transfer_enabled = not app.ownership_transfer_enabled
        if "orphan" in request.path:
            app.is_orphan = not app.is_orphan
        app.save()
        return redirect(reverse("user:account-transfer-apps"))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["apps"] = App.objects.filter(owner=self.request.user)
        context["acc_page"] = "account-transfer-apps"
        return context


@method_decorator(never_cache, name="dispatch")
class EnterpriseAppsView(LoginRequiredMixin, TemplateView):
    template_name = "user/enterprise-apps.html"

    def post(self, request, pk):
        app = get_object_or_404(App, pk=pk, owner=self.request.user)
        app.is_enterprise_supported = not app.is_enterprise_supported
        app.save()
        return redirect(reverse("user:account-enterprise-apps"))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["apps"] = App.objects.filter(owner=self.request.user)
        context["acc_page"] = "account-enterprise-apps"
        return context


@method_decorator(never_cache, name="dispatch")
class ChangeLanguageView(LoginRequiredMixin, TemplateView):
    template_name = "user/set-language.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["acc_page"] = "account-change-language"
        return context


@method_decorator(never_cache, name="dispatch")
class DeleteAccountView(LoginRequiredMixin, TemplateView):
    template_name = "user/delete-account.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = DeleteAccountForm()
        context["acc_page"] = "delete-account"
        return context

    def post(self, request, *args, **kwargs):
        form = DeleteAccountForm(request.POST, user=request.user)
        if not form.is_valid():
            return render(request, self.template_name, {"form": form})

        request.user.delete()
        return redirect(reverse_lazy("home"))


@method_decorator(never_cache, name="dispatch")
class AccountView(LoginRequiredMixin, UpdateView):
    """Display and allow changing of the user's name and subscription."""

    template_name = "user/account.html"
    template_name_suffix = ""
    form_class = AccountForm
    success_url = reverse_lazy("user:account")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["acc_page"] = "account"
        return context

    def form_invalid(self, form):
        failed_attempts = self.request.session.get("account_update_failed_count", 0)
        if failed_attempts >= 15:
            logout(self.request)
            return HttpResponseRedirect("/")
        self.request.session["account_update_failed_count"] = failed_attempts + 1
        return super().form_invalid(form)

    def form_valid(self, form):
        message = "Account details saved."

        user = self.request.user
        current_email = EmailAddress.objects.get_primary(user=user).email
        new_email = form.cleaned_data["email"]
        if new_email != current_email:
            # Delete other unconfirmed email addresses
            EmailAddress.objects.filter(user=user).exclude(primary=True).delete()
            # Add new email address, send confirmation email
            EmailAddress.objects.add_email(self.request, user, new_email, confirm=True)
            message += f" Please verify your email address from the confirmation email sent to {new_email}."

        # Update subscription preference
        user.profile.subscribe_to_news = form.cleaned_data["subscribe_to_news"]
        user.profile.save()

        messages.success(self.request, message)
        self.request.session["account_update_failed_count"] = 0
        return super().form_valid(form)

    def get_object(self, queryset=None):
        return self.request.user


@method_decorator(never_cache, name="dispatch")
class PasswordView(LoginRequiredMixin, PasswordChangeView):
    """Allow the user to change their password."""

    template_name = "user/password.html"
    success_url = reverse_lazy("user:account-password")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["acc_page"] = "password"
        return context


@method_decorator(never_cache, name="dispatch")
class APITokenView(LoginRequiredMixin, TemplateView):
    """Display the user's API token, and allow it to be regenerated."""

    template_name = "user/api-token.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["acc_page"] = "api-token"
        return context


@method_decorator(never_cache, name="dispatch")
class AppealCommentsView(LoginRequiredMixin, TemplateView):
    template_name = "user/appeal-comments.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_superuser:
            # context["pending"] = AppRating.objects.filter(appeal=True)
            pending_ratings = AppRating.objects.filter(appeal=True)
            pending_with_lang = [
                {
                    "rating": rating,
                    "lang": rating.translations.first().language_code if rating.translations.exists() else None,
                }
                for rating in pending_ratings
            ]
            context["pending"] = pending_with_lang
        context["acc_page"] = "appeal-comments"
        return context

appstore/nextcloudappstore/user/templates/user/account.html
{% extends "user/base.html" %}
{% load i18n %}
{% load static %}

{# SPDX-FileCopyrightText: 2017 Nextcloud GmbH and Nextcloud contributors #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% block head-title %}{% trans 'Account' %} - {% endblock %}

{% block account-content %}
    <h1>{% trans "Account" %}</h1>
    <section>
        <form action="{% url 'user:account' %}" method="post">
            {% include 'form-fields.html' %}
            <p>
                <button class="btn btn-primary btn-block" type="submit">
                    <span class="icon material-symbols-outlined">done</span>
                    {% trans 'Save' %}
                </button>
            </p>
        </form>
    </section>
{% endblock %}

appstore/nextcloudappstore/user/templates/user/api-token.html
{% extends "user/base.html" %}
{% load i18n %}
{% load static %}

{# SPDX-FileCopyrightText: 2017 Nextcloud GmbH and Nextcloud contributors #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% block head %}
    <script defer src="{% static 'public/user/token.js' %}"></script>
{% endblock %}

{% block head-title %}{% trans 'API Token' %} - {% endblock %}

{% block account-content %}
    <h1>{% trans "API Token" %}</h1>
    <section id="tokenSection">
        <p>
            {% blocktrans %}
                The API token can be used for authentication when calling the Nextcloud app store
                <a href="https://nextcloudappstore.readthedocs.io/en/latest/restapi.html">REST API</a>.
                Make sure to keep it secret. A new token can be generated below, rendering the old token invalid.
            {% endblocktrans %}
        </p>

        <p>{% trans 'Your API token is:' %}</p>

        <!-- DO NOT print the HTML token here because of BREACH attack but fetch it with JS -->
        <p><code id="token"></code></p>
        <form action="{% url 'api:v1:user-token-new' %}" method="post" id="api-token-regen-form">
            <span data-l10n-id="msg-form-success" hidden>{% trans 'New API token generated.' %}</span>
            <div><div class="hidden alert alert-success global-success-msg" hidden></div></div>
            <div><div class="alert alert-danger global-error-msg" hidden></div></div>

            {% csrf_token %}
            <input type="submit" class="btn btn-primary btn-block" value="{% trans 'Regenerate API token' %}" disabled="disabled">
        </form>
    </section>
{% endblock %}

appstore/nextcloudappstore/user/templates/user/appeal-comments.html
{% extends "user/base.html" %}
{% load i18n %}
{% load static %}

{# SPDX-FileCopyrightText: 2023 Nextcloud GmbH and Nextcloud contributors #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% block head-title %}{% trans 'Appeal commentaries' %} - {% endblock %}

{% block account-content %}
    {% if user.is_superuser %}
        <h1>{% trans "Comments Pending Appeal" %}</h1>
        <section>
            <table class="table table-striped">
                <tr>
                    <th>{% trans 'App' %}</th>
                    <th>{% trans 'Comment author' %}</th>
                    <th>{% trans 'Link' %}</th>
                </tr>
                {% for item in pending %}
                    <tr>
                        <td>{{ item.rating.app }}</td>
                        <td>{{ item.rating.user }}</td>
                        <td>
                            <form action="{% url 'app-detail' id=item.rating.app.id %}" method="get">
                                <input type="hidden" name="comment_id" value="{{ item.rating.id }}">
                                <input type="hidden" name="bad_comment_lang" value="{{ item.lang }}">
                                <button class="btn btn-primary btn-block" type="submit">{% trans 'Go to' %}</button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </section>
    {% endif %}

{% endblock %}

appstore/nextcloudappstore/user/templates/user/base.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{# SPDX-FileCopyrightText: 2017 Nextcloud GmbH and Nextcloud contributors #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% block head-title %}{% trans "Account" %} - {% endblock %}

{% block content %}
<div class="row">
    <div class="col-sm-4 col-md-3">
        <ul id="sidebar" class="nav nav-pills nav-stacked">
            <li class="{% if acc_page == 'account' %}active{% endif %}">
                <a href="{% url 'user:account' %}">
                    <span class="icon material-symbols-outlined">person</span>
                    {% trans 'Account' %}
                </a>
            </li>
            <li class="{% if acc_page == 'account-integrations' %}active{% endif %}">
                <a href="{% url 'user:account-integrations' %}">
                    <span class="icon material-symbols-outlined">integration_instructions</span>
                    {% trans 'Integrations' %}
                </a>
            </li>
            <li class="{% if acc_page == 'account-transfer-apps' %}active{% endif %}">
                <a href="{% url 'user:account-transfer-apps' %}">
                    <span class="icon material-symbols-outlined">move_down</span>
                    {% trans 'Transfer app ownership' %}
                </a>
            </li>
            <li class="{% if acc_page == 'account-enterprise-apps' %}active{% endif %}">
                <a href="{% url 'user:account-enterprise-apps' %}">
                    <span class="icon material-symbols-outlined">enterprise</span>
                    {% trans 'Enterprise support' %}
                </a>
            </li>
            <li class="{% if acc_page == 'account-change-language' %}active{% endif %}">
                <a href="{% url 'user:account-change-language' %}">
                    <span class="icon material-symbols-outlined">translate</span>
                    {% trans 'Change language' %}
                </a>
            </li>
            {% if request.user.has_usable_password %}
                <li class="{% if acc_page == 'password' %}active{% endif %}">
                    <a href="{% url 'user:account-password' %}">
                        <span class="icon material-symbols-outlined">password</span>
                        {% trans 'Password' %}
                    </a>
                </li>
            {% endif %}
            <li class="{% if acc_page == 'api-token' %}active{% endif %}">
                <a href="{% url 'user:account-api-token' %}">
                    <span class="icon material-symbols-outlined">key</span>
                    {% trans 'API token' %}
                </a>
            </li>
            <li class="{% if acc_page == 'delete-account' %}active{% endif %}">
                <a href="{% url 'user:account-deletion' %}">
                    <span class="icon material-symbols-outlined">security</span>
                    {% trans 'Delete account' %}
                </a>
            </li>
            {% if user.is_superuser %}
                <li class="{% if acc_page == 'appeal-comments' %}active{% endif %}">
                    <a href="{% url 'user:appeal-comments' %}">
                        <span class="icon material-symbols-outlined">flag</span>
                        {% trans 'Appeal comments' %}
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>
    <div class="col-sm-8 col-md-9 account-content">
        {% block account-content %}{% endblock %}
    </div>
</div>
{% endblock %}

appstore/nextcloudappstore/user/templates/user/delete-account.html
{% extends "user/base.html" %}
{% load i18n %}
{% load account socialaccount css_class %}

{# SPDX-FileCopyrightText: 2017 Nextcloud GmbH and Nextcloud contributors #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% block head-title %}{% trans "Delete account" %} - {% endblock %}

{% block account-content %}
    <h1>{% trans "Delete account" %}</h1>
    <section>
        <p class="alert alert-danger">{% trans 'Deleting your account will delete all your apps and releases as well. To delete your account, insert your email address into the input field and click the "Delete account" button.' %}</p>
        <form method="POST" action="{% url 'user:account-deletion' %}">
            {% include 'form-fields.html' %}
{#            <p><input type="submit" class="btn btn-danger" value="{% trans 'Delete account' %}"></p>#}
            <p>
                <button type="submit" class="btn btn-danger">
                    <span class="icon material-symbols-outlined">person_remove</span>
                    {% trans 'Delete account' %}
                </button>
            </p>
        </form>
    </section>
{% endblock %}

appstore/nextcloudappstore/user/templates/user/enterprise-apps.html
{% extends "user/base.html" %}
{% load i18n %}
{% load static %}

{# SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% block head-title %}{% trans 'Enterprise App Support' %} - {% endblock %}

{% block account-content %}
    <h1>{% trans 'Enterprise App Support' %}</h1>
    <section>
        <p>{% trans "If an app is available to receive enterprise support, you can mark the app as such here. This will add a 'Request quote' button to the app's details page in the App Store and in Nextcloud Apps. Such support can only be requested for large Nextcloud installations." %}</p>

        {% if apps %}
            <table class="table table-striped transfer-apps">
                <tr>
                    <th>{% trans 'App name' %}</th>
                    <th>{% trans 'Support status' %}</th>
                    <th>{% trans 'Change support status' %}</th>
                </tr>
                {% for app in apps %}
                    <tr>
                        <td>{{ app.name }}</td>
                        <td class="{% if app.is_enterprise_supported %}bg-success{% else %}bg-danger{% endif %}">
                            {% if app.is_enterprise_supported %}
                                {% trans 'Supported' %}
                            {% else %}
                                {% trans 'Unsupported' %}
                            {% endif %}
                        </td>
                        <td>
                            <form action="{% url 'user:account-enterprise-app' pk=app.id %}" method="post">
                                {% csrf_token %}
                                {% if app.is_enterprise_supported %}
                                    <button class="btn btn-primary btn-block" type="submit">{% trans 'Mark as unsupported' %}</button>
                                {% else %}
                                    <button class="btn btn-primary btn-block" type="submit">{% trans 'Mark as supported' %}</button>
                                {% endif %}
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        {% else %}
            <p class="alert alert-info">{% trans 'You have not uploaded any apps yet!' %}</p>
        {% endif %}
    </section>
{% endblock %}

appstore/nextcloudappstore/user/templates/user/integrations.html
{% extends "user/base.html" %}
{% load i18n %}
{% load static %}

{# SPDX-FileCopyrightText: 2020 Nextcloud GmbH and Nextcloud contributors #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% block head-title %}{% trans 'Integrations' %} - {% endblock %}

{% block account-content %}
    {% if pending and user.is_superuser %}
        <h1>{% trans "Pending approval" %}</h1>
        <section>
            <table class="table table-striped">
                <tr>
                    <th>{% trans 'Integration name' %}</th>
                    <th>{% trans 'Actions' %}</th>
                </tr>
                {% for app in pending %}
                    <tr>
                        <td>{{ app.name }}</td>
                        <td>
                            <form action="{% url 'user:account-integration-moderate' pk=app.id %}" method="get">
                                {% csrf_token %}
                                <button class="btn btn-primary btn-block" type="submit">{% trans 'View' %}</button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </section>
    {% endif %}

    <h1>{% trans "Your integrations" %}</h1>
    <section>
        {% if apps %}
            <table class="table table-striped">
                <tr>
                    <th>{% trans 'Integration name' %}</th>
                    <th>{% trans 'Actions' %}</th>
                </tr>
                {% for app in apps %}
                    <tr>
                        <td>{{ app.name }}</td>
                        <td>
                            <form action="{% url 'user:account-integration' pk=app.id %}" method="get">
                                {% csrf_token %}
                                <button class="btn btn-primary btn-block" type="submit">{% trans 'Edit' %}</button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        {% else %}
            <p class="alert alert-info">{% trans 'You have not submitted any integration yet or they are pending approval!' %}</p>
        {% endif %}
    </section>
{% endblock %}

appstore/nextcloudappstore/user/templates/user/transfer-apps.html
{% extends "user/base.html" %}
{% load i18n %}
{% load static %}

{# SPDX-FileCopyrightText: 2017 Nextcloud GmbH and Nextcloud contributors #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% block head-title %}{% trans 'Transfer Apps' %} - {% endblock %}

{% block account-content %}
    <h1>{% trans "Transfer Apps" %}</h1>
    <section>
        <p>{% trans 'To transfer an app to a new owner you must first unlock the app. A user can then take control of the app by registering it again on the app register page in the app developer menu.' %}</p>
        <p>{% trans "Don't have a new owner yet? You can mark the app as orphaned to indicate that you are looking for a new owner. Once the transfer is complete, the app will be automatically marked as un-orphaned/maintained again." %}</p>

        {% if apps %}
            <table class="table table-striped transfer-apps">
                <tr>
                    <th>{% trans 'App name' %}</th>
                    <th>{% trans 'Ownership transfer status' %}</th>
                    <th>{% trans 'App status' %}</th>
                    <th>{% trans 'Change ownership transfer status' %}</th>
                    <th>{% trans 'Change app status' %}</th>
                </tr>
                {% for app in apps %}
                    <tr>
                        <td>{{ app.name }}</td>
                        <td class="{% if app.ownership_transfer_enabled %}bg-success{% else %}bg-danger{% endif %}">
                            {% if app.ownership_transfer_enabled %}
                                {% trans 'Unlocked' %}
                            {% else %}
                                {% trans 'Locked' %}
                            {% endif %}
                        </td>
                        <td class="{% if app.is_orphan %}bg-danger{% else %}bg-success{% endif %}">
                            {% if app.is_orphan %}
                                {% trans 'Orphaned' %}
                            {% else %}
                                {% trans 'Maintained' %}
                            {% endif %}
                        </td>
                        <td>
                            <form action="{% url 'user:account-transfer-app' pk=app.id %}" method="post">
                                {% csrf_token %}
                                {% if app.ownership_transfer_enabled %}
                                    <button class="btn btn-primary btn-block" type="submit">{% trans 'Lock ownership transfer' %}</button>
                                {% else %}
                                    <button class="btn btn-primary btn-block" type="submit">{% trans 'Unlock ownership transfer' %}</button>
                                {% endif %}
                            </form>
                        </td>
                        <td>
                            <form action="{% url 'user:account-orphan-app' pk=app.id %}" method="post">
                                {% csrf_token %}
                                {% if app.is_orphan %}
                                    <button class="btn btn-primary btn-block" type="submit">{% trans 'Mark as maintained' %}</button>
                                {% else %}
                                    <button class="btn btn-primary btn-block" type="submit">{% trans 'Mark as orphaned' %}</button>
                                {% endif %}
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        {% else %}
            <p class="alert alert-info">{% trans 'You have not uploaded any apps yet!' %}</p>
        {% endif %}
    </section>
{% endblock %}