appstore/nextcloudappstore/urls.py
"""
SPDX-FileCopyrightText: 2016 Nextcloud GmbH and Nextcloud contributors
SPDX-License-Identifier: AGPL-3.0-or-later
"""

from allauth.account.views import signup
from allauth.socialaccount.views import signup as social_signup
from csp.decorators import csp_update
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import include, path, re_path
from django.views.decorators.http import etag

from nextcloudappstore.core.caching import app_rating_etag
from nextcloudappstore.core.feeds import AppReleaseAtomFeed, AppReleaseRssFeed
from nextcloudappstore.core.views import (
    AppDetailView,
    AppRatingApi,
    AppRegisterView,
    AppReleasesView,
    AppUploadView,
    CategoryAppListView,
    app_description,
)
from nextcloudappstore.scaffolding.views import (
    AppScaffoldingView,
    IntegrationScaffoldingView,
)

admin.site.login = login_required(admin.site.login)

urlpatterns = [
    path("", CategoryAppListView.as_view(), {"id": None}, name="home"),
    path("featured", CategoryAppListView.as_view(), {"id": None, "is_featured_category": True}, name="featured"),
    path("signup/", csp_update(**settings.CSP_SIGNUP)(signup), name="account_signup"),
    path("social/signup/", csp_update(**settings.CSP_SIGNUP)(social_signup), name="socialaccount_signup"),
    path("", include("allauth.urls")),
    re_path(r"^categories/(?P<id>[\w]*)/?$", CategoryAppListView.as_view(), name="category-app-list"),
    re_path(r"^developer/apps/generate/?$", AppScaffoldingView.as_view(), name="app-scaffold"),
    re_path(r"^developer/integration/new/?$", IntegrationScaffoldingView.as_view(), name="integration-scaffold"),
    re_path(r"^developer/apps/releases/new/?$", AppUploadView.as_view(), name="app-upload"),
    re_path(r"^developer/apps/new/?$", AppRegisterView.as_view(), name="app-register"),
    re_path(r"^apps/(?P<id>[\w_]+)/?$", AppDetailView.as_view(), name="app-detail"),
    re_path(r"^apps/(?P<id>[\w_]+)/releases/?$", AppReleasesView.as_view(), name="app-releases"),
    re_path(r"^apps/(?P<id>[\w_]+)/description/?$", app_description, name="app-description"),
    re_path(r"^apps/(?P<id>[\w_]+)/ratings.json$", etag(app_rating_etag)(AppRatingApi.as_view()), name="app-ratings"),
    path("api/", include("nextcloudappstore.api.urls", namespace="api")),
    path("account/", include("nextcloudappstore.user.urls", namespace="user")),
    re_path(r"^admin/", admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
    path("captcha/", include("captcha.urls")),
]

urlpatterns += i18n_patterns(
    re_path(r"feeds/releases.rss", AppReleaseRssFeed(), name="feeds-releases-rss"),
    re_path(r"feeds/releases.atom", AppReleaseAtomFeed(), name="feeds-releases-atom"),
)

if settings.DEBUG:
    try:
        import debug_toolbar

        urlpatterns += [
            path("__debug__/", include(debug_toolbar.urls)),
        ]
    except ImportError:
        pass

appstore/nextcloudappstore/user/urls.py
"""
SPDX-FileCopyrightText: 2017 Nextcloud GmbH and Nextcloud contributors
SPDX-License-Identifier: AGPL-3.0-or-later
"""

from django.urls import path, re_path

from nextcloudappstore.scaffolding.views import IntegrationScaffoldingView
from nextcloudappstore.user.views import (
    AccountView,
    APITokenView,
    AppealCommentsView,
    ChangeLanguageView,
    DeleteAccountView,
    EnterpriseAppsView,
    IntegrationsView,
    PasswordView,
    TransferAppsView,
)

app_name = "user"

urlpatterns = [
    path("", AccountView.as_view(), name="account"),
    re_path(r"^integrations/?$", IntegrationsView.as_view(), name="account-integrations"),
    re_path(r"^integrations/(?P<pk>[a-z0-9_]+)/?$", IntegrationScaffoldingView.as_view(), name="account-integration"),
    re_path(
        r"^integrations/(?P<pk>[a-z0-9_]+)/moderate/?$",
        IntegrationScaffoldingView.as_view(),
        name="account-integration-moderate",
    ),
    re_path(r"^transfer-apps/?$", TransferAppsView.as_view(), name="account-transfer-apps"),
    re_path(r"^transfer-apps/(?P<pk>[a-z0-9_]+)/?$", TransferAppsView.as_view(), name="account-transfer-app"),
    re_path(r"^orphan-apps/(?P<pk>[a-z0-9_]+)/?$", TransferAppsView.as_view(), name="account-orphan-app"),
    re_path(r"^enterprise-apps/?$", EnterpriseAppsView.as_view(), name="account-enterprise-apps"),
    re_path(r"^enterprise-apps/(?P<pk>[a-z0-9_]+)/?$", EnterpriseAppsView.as_view(), name="account-enterprise-app"),
    re_path(r"^password/?$", PasswordView.as_view(), name="account-password"),
    re_path(r"^token/?$", APITokenView.as_view(), name="account-api-token"),
    re_path(r"^delete/?$", DeleteAccountView.as_view(), name="account-deletion"),
    re_path(r"^change-language/?$", ChangeLanguageView.as_view(), name="account-change-language"),
    re_path(r"^appeal-comments/?$", AppealCommentsView.as_view(), name="appeal-comments"),
]

appstore/nextcloudappstore/core/views.py
"""
SPDX-FileCopyrightText: 2016 Nextcloud GmbH and Nextcloud contributors
SPDX-License-Identifier: AGPL-3.0-or-later
"""

import json
from urllib.parse import urlencode

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.utils.functional import cached_property
from django.utils.translation import get_language, get_language_info
from django.views.decorators.http import etag
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from rest_framework.generics import ListAPIView
from semantic_version import Version

from nextcloudappstore.core.caching import app_etag
from nextcloudappstore.core.facades import flatmap
from nextcloudappstore.core.forms import (
    AppRatingForm,
    AppRegisterForm,
    AppReleaseUploadForm,
)
from nextcloudappstore.core.models import App, AppRating, Category, Donation, Podcast
from nextcloudappstore.core.serializers import AppRatingSerializer
from nextcloudappstore.core.versioning import pad_min_version


@etag(app_etag)
def app_description(request, id):
    app = get_object_or_404(App, id=id)
    return HttpResponse(app.description, content_type="text/plain")


class AppRatingApi(ListAPIView):
    serializer_class = AppRatingSerializer

    def get_queryset(self):
        id = self.kwargs.get("id")
        lang = self.request.GET.get("lang", self.request.LANGUAGE_CODE)
        app = get_object_or_404(App, id=id)
        queryset = AppRating.objects.language(lang).filter(app=app)

        current_user = self.request.GET.get("current_user", "false")
        if current_user == "true":
            return queryset.filter(user=self.request.user)
        else:
            return queryset


class AppDetailView(DetailView):
    queryset = App.objects.prefetch_related(
        "releases",
        "screenshots",
        "co_maintainers",
        "translations",
    ).select_related("owner")
    template_name = "app/detail.html"
    slug_field = "id"
    slug_url_kwarg = "id"

    def post(self, request, id):
        post_data = json.loads(request.body) if request.content_type == "application/json" else request.POST
        if request.user.is_authenticated and ("decision" in post_data or "appeal" in post_data):
            app_rating, created = AppRating.objects.get_or_create(id=post_data["comment_id"], app=id)
            if not created:
                # ignore request that comes for non-existing comments
                if "decision" in post_data and request.user.is_superuser:
                    # admin made a decision
                    if bool(post_data["decision"]):
                        app_rating.delete()
                    else:
                        app_rating.appeal = False
                        app_rating.save()
                elif "appeal" in post_data and "comment_id" in post_data and app_rating.app.owner == request.user:
                    # author of App marked comment
                    app_rating.appeal = bool(post_data["appeal"])
                    app_rating.save()
        else:
            form = AppRatingForm(request.POST, id=id, user=request.user)
            # there is no way that a rating can be invalid by default
            if form.is_valid() and request.user.is_authenticated:
                form.save()
        return redirect("app-detail", id=id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["DISCOURSE_URL"] = settings.DISCOURSE_URL.rstrip("/")
        context["rating_form"] = AppRatingForm(initial={"language_code": get_language()})

        ratings = AppRating.objects.filter(app=context["app"])
        rating_languages = flatmap(lambda r: r.get_available_languages(), ratings)

        # make sure current session language is in the list even if there are
        # no comments.
        rating_languages = list(rating_languages)
        if get_language() not in rating_languages:
            rating_languages.append(get_language())

        context["languages"] = set(sorted(rating_languages))
        context["fallbackLang"] = "en" if "en" in context["languages"] else ""
        context["user_has_rated_app"] = False
        if self.request.user.is_authenticated:
            try:
                app_rating = AppRating.objects.get(user=self.request.user, app=context["app"])

                # if parler falls back to a fallback language
                # it doesn't set the language as current language
                # and we can't select the correct language in the
                # frontend. So we try and find a languge that is
                # available
                language_code = app_rating.get_current_language()
                if not app_rating.has_translation(language_code):
                    for fallback in app_rating.get_fallback_languages():
                        if app_rating.has_translation(fallback):
                            app_rating.set_current_language(fallback)

                # when accessing an empty comment django-parler tries to
                # fall back to the default language. However for comments
                # the default (English) does not always exist. Unfortunately
                # it throws the same exception as non existing models,
                # so we need to access it beforehand
                try:
                    comment = app_rating.comment
                except AppRating.DoesNotExist:
                    comment = ""

                context["rating_form"] = AppRatingForm(
                    {
                        "rating": app_rating.rating,
                        "comment": comment,
                        "language_code": app_rating.get_current_language(),
                    }
                )
                context["user_has_rated_app"] = True
            except AppRating.DoesNotExist:
                pass

        context["donations"] = Donation.objects.filter(app=context["app"])
        context["categories"] = Category.objects.prefetch_related("translations").all()
        context["latest_releases_by_platform_v"] = self.object.latest_releases_by_platform_v()
        context["is_integration"] = self.object.is_integration
        context["is_outdated"] = self.object.is_outdated()

        return context


class AppReleasesView(DetailView):
    queryset = App.objects.prefetch_related(
        "translations",
        "releases__translations",
        "releases__phpextensiondependencies__php_extension",
        "releases__databasedependencies__database",
        "releases__shell_commands",
        "releases__licenses",
    )
    template_name = "app/releases.html"
    slug_field = "id"
    slug_url_kwarg = "id"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.prefetch_related("translations").all()

        releases = self.object.releases_by_platform_v()
        unstables = self.object.unstable_releases_by_platform_v()
        versions = set(list(releases.keys()) + list(unstables.keys()))
        all_releases = list(map(lambda v: (v, releases.get(v, []) + unstables.get(v, [])), versions))
        context["releases_by_platform_v"] = self._sort_by_platform_v(all_releases)
        return context

    def _sort_by_platform_v(self, releases_by_platform, reverse=True):
        """Sorts a list of tuples like (<platform version>, [releases]) by
        platform version.

        :param releases_by_platform: A list of tuples.
        :param reverse: Descending order if True, ascending otherwise.
        :return sorted list of tuples.
        """

        return sorted(releases_by_platform, reverse=reverse, key=lambda v: Version(pad_min_version(v[0])))


class CategoryAppListView(ListView):
    model = App
    template_name = "app/list.html"
    allow_empty = True

    def get_queryset(self):
        order_by = self.request.GET.get("order_by", "relevance")
        ordering = self.request.GET.get("ordering", "desc")
        is_featured = self.request.GET.get("is_featured", False)
        maintainer = self.request.GET.get("maintainer", False)
        sort_columns = []

        if self.kwargs.get("is_featured_category", False):
            is_featured = "true"

        allowed_order_by = {"name", "last_release", "rating_overall", "rating_recent", "relevance"}
        if order_by in allowed_order_by:
            if order_by == "name":
                order_by = "translations__name"
            if ordering == "desc":
                sort_columns.append("-" + order_by)
            else:
                sort_columns.append(order_by)

        lang = get_language_info(get_language())["code"]
        category_id = self.kwargs["id"]

        if order_by == "relevance":
            queryset = App.objects.search_relevant(self.search_terms, lang)
        else:
            queryset = App.objects.search(self.search_terms, lang).order_by(*sort_columns)
        queryset = queryset.filter(Q(releases__gt=0) | (Q(is_integration=True) & Q(approved=True)))

        if maintainer:
            try:
                user = User.objects.get_by_natural_key(maintainer)
                queryset = queryset.filter(Q(owner=user) | Q(co_maintainers=user))
            except ObjectDoesNotExist:
                return queryset.none()
        if category_id:
            queryset = queryset.filter(categories__id=category_id)
        if is_featured == "true":
            queryset = queryset.filter(is_featured=True)
        return queryset.prefetch_related("screenshots", "translations")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

appstore/nextcloudappstore/core/templates/429.html
{% extends 'base.html' %}
{% load i18n %}

{# SPDX-FileCopyrightText: 2023 Nextcloud GmbH and Nextcloud contributors #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% block head-title %}{% trans 'Forbidden' %} - {% endblock %}

{% block content %}

    <h1>{% trans 'Forbidden' %}</h1>

    <p>{% trans 'Too many tries. Try again in a few minutes.' %}</p>

{% endblock %}

appstore/nextcloudappstore/core/templates/base.html
{% load static %}
{% load i18n %}
{# SPDX-FileCopyrightText: 2016 Nextcloud GmbH and Nextcloud contributors #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}
<!DOCTYPE html>
<html lang="{{ request.LANGUAGE_CODE }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% trans 'The Nextcloud App Store - Upload your apps and install new apps onto your Nextcloud' %}">
    <meta name="author" content="{% trans 'The Nextcloud Community' %}">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel="shortcut icon" href="{% static 'assets/img/favicon.png' %}"/>
    <link rel="apple-touch-icon" href="{% static 'assets/img/favicon-180.png' %}">
    <title>{% block head-title %}{% endblock %}App Store - Nextcloud</title>
    <link rel="stylesheet" href="{% static 'assets/css/fonts.css' %}" charset="utf-8">
    <link rel="stylesheet"
          href="{% static 'vendor/bootstrap/dist/css/bootstrap.min.css' %}" charset="utf-8">
    <link rel="stylesheet" href="{% static 'assets/css/icons.css' %}" charset="utf-8">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" charset="utf-8">
    <link rel="stylesheet" href="{% static 'assets/css/theme.css' %}" charset="utf-8">
    {% block feeds %}
        <link rel="alternate" type="application/atom+xml" title="{% trans 'Latest app releases' %}" href="{% url 'feeds-releases-atom' %}" />
        <link rel="alternate" type="application/rss+xml" title="{% trans 'Latest app releases' %}" href="{% url 'feeds-releases-rss' %}" />
    {% endblock %}
    <script type="text/javascript" src="{% static 'vendor/bootstrap.native.min.js' %}" async></script>
    {% block head %}{% endblock %}
</head>

<body>
<div id="container">
    {% block navbar %}{% include 'nav.html' %}{% endblock %}
    <div class="container" id="body">
        <div class="messages">
            {% for message in messages %}
                <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
                    {{ message }}
                </div>
            {% endfor %}
            {% block messages %}{% endblock %}
        </div>
        {% block content %}{% endblock %}
    </div>
    <footer class="navbar-default" id="footer">
        <div class="container">
            <ul class="nav navbar-nav">
                <li class="nav-link">
                    <a href="https://github.com/nextcloud/appstore" rel="noreferrer noopener">
                        <span class="icon icon-source-fork"></span>
                        {% trans 'Contribute to the app store' %}
                    </a>
                </li>
                <li class="nav-link">
                    <a href="https://nextcloud.com/privacy/" rel="noreferrer noopener">
                        <span class="icon icon-text-box-outline"></span>
                        {% trans 'Privacy and legal' %}
                    </a>
                </li>
                <li class="nav-link">
                    <a href="https://nextcloud.com/impressum/" rel="noreferrer noopener">
                        <span class="icon icon-note-text-outline"></span>
                        {% trans 'Legal notice' %}
                    </a>
                </li>
            </ul>
        </div>
    </footer>
</div>
</body>
</html>

appstore/nextcloudappstore/core/templates/form-fields.html
{% load css_class field_type i18n %}
{% csrf_token %}
{# SPDX-FileCopyrightText: 2016 Nextcloud GmbH and Nextcloud contributors #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}
{% if form.non_field_errors  %}
    {% for error in form.non_field_errors %}
        <span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
        <span class="sr-only">(error)</span>
        <p class="text-danger">{{ error }}</p>
    {% endfor %}
{% endif %}
{% for field in form.visible_fields %}
    <div class="form-group {% if field.errors %}has-error has-feedback{% endif %}">

        {% if field|field_type == 'CheckboxInput' %}

            <label class="control-label checkbox-group" for="{{ field.id_for_label }}">
                {{ field.label }}
                {{ field }}
                <span class="checkmark"></span>
            </label>
        {% else %}

            {% if field.field.required %}
                <label title="{% trans 'required field' %}" class="control-label" for="{{ field.id_for_label }}">
                    {{ field.label }}
                    <span class="required-field material-symbols-outlined">asterisk</span>
                </label>
            {% else %}
                <label class="control-label" for="{{ field.id_for_label }}">
                    {{ field.label }}
                </label>
            {% endif %}

            {% if field|field_type == 'RadioSelect' %}
                {{ field }}
            {% else %}
                {{ field|css_class:'form-control' }}
            {% endif %}

        {% endif %}

        {% if field.errors %}
            {% for error in field.errors %}
                <span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                <span class="sr-only">(error)</span>
                <p class="text-danger">{{ error }}</p>
            {% endfor %}
        {% endif %}

        <!-- javascript errors -->
        <div hidden>
            <span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
            <span class="sr-only">(error)</span>
            <p class="text-danger error-msg-{{field.name}}"></p>
        </div>

        {% if field.help_text %}
            {% if form.safe_help_fields and field.name in form.safe_help_fields %}
                <p class="help-block">{{ field.help_text|safe }}</p>
            {% else %}
                <p class="help-block">{{ field.help_text }}</p>
            {% endif %}
        {% endif %}
    </div>
{% endfor %}
{% if redirect_field_value %}
    <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
{% endif %}

appstore/nextcloudappstore/core/templates/nav.html
{% load static %}
{% load i18n %}
{# SPDX-FileCopyrightText: 2016 Nextcloud GmbH and Nextcloud contributors #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}
<div class="banner">
    <div class="container">
        <div class="row row-no-gutters">
            <div class="col-md-12 col-lg-6">
                <div class="left-navbar-wrapper">
                    <a class="brand" href="/">
                        <img class="logo" alt="Logo" src="{% static 'assets/img/logo-icon.svg' %}" title="nextcloud.com">
                        <span class="site-title">App store</span>
                    </a>
                    <ul class="nav navbar-nav developer-nav">
                        <li role="presentation" class="dropdown">
                            <a class="dropdown-toggle nav-heading" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                                <span class="icon material-symbols-outlined">arrow_drop_down_circle</span>
                                {% trans 'Resources for developers' %}
                            </a>
                            <ul class="dropdown-menu">
                                <li class="nav-link">
                                    <a href="https://nextcloud.com/developer" rel="noopener noreferrer">
                                        <span class="icon material-symbols-outlined">developer_board</span>
                                        {% trans 'Develop for Nextcloud' %}
                                    </a>
                                </li>
                                <li class="nav-link">
                                    <a href="https://docs.nextcloud.com/server/latest/developer_manual" rel="noopener noreferrer">
                                        <span class="icon material-symbols-outlined">description</span>
                                        {% trans 'Developer documentation' %}
                                    </a>
                                </li>
                                <li class="nav-link">
                                    <a href="https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html" rel="noopener noreferrer">
                                        <span class="icon material-symbols-outlined">translate</span>
                                        {% trans 'Request translations' %}
                                    </a>
                                </li>
                                <li role="separator" class="divider"></li>
                                <li class="nav-link">
                                    <a href="https://nextcloudappstore.readthedocs.io/en/latest/developer.html" rel="noopener noreferrer">
                                        <span class="icon material-symbols-outlined">upload</span>
                                        {% trans 'Submit your app' %}
                                    </a>
                                </li>
                                <li class="nav-link">
                                    <a href="{% url 'app-scaffold' %}">
                                        <span class="icon icon-creation-outline"></span>
                                        {% trans 'Generate app' %}
                                    </a>
                                </li>
                                {% if request.user.is_authenticated %}
                                    <li role="separator" class="divider"></li>
                                    <li class="nav-link">
                                        <a href="{% url 'app-register' %}">
                                            <span class="icon material-symbols-outlined">publish</span>
                                            {% trans 'Register app' %}
                                        </a>
                                    </li>
                                    <li class="nav-link">
                                        <a href="{% url 'app-upload' %}">
                                            <span class="icon material-symbols-outlined">backup</span>
                                            {% trans 'Upload app release' %}
                                        </a>
                                    </li>
                                {% endif %}
                                {% if request.user.is_authenticated %}
                                    <li class="nav-link">
                                        <a href="{% url 'integration-scaffold' %}">
                                            <span class="icon material-symbols-outlined">integration_instructions</span>
                                            {% trans 'Register integration' %}
                                        </a>
                                    </li>
                                {% endif %}
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-12 col-lg-6">
                <div id="navbar-wrapper" class="navbar-wrapper">
                    <div class="search-form">
                        <form method="get"
                              action="{% if current_category %}{{ request.path }}
                              {% else %}{% url 'home' %}
                              {% endif %}">
                            <div class="search-input-group">
                                <span class="icon material-symbols-outlined" aria-hidden="true">search</span>
                                <input type="search"
                                       name="search"
                                       role="search"
                                       value="{{ search_query }}"
                                       placeholder="{% if current_category %}{% blocktrans with category=current_category.name %}Search in {{ category }}{% endblocktrans %}{% elif is_featured_category %}{% trans 'Search in featured apps' %}{% else %}{% trans 'Search in all apps' %}{% endif %}"
                                       class="form-control search-box">
                            </div>

                            {# Include all GET arguments that should be preserved when searching. #}
                            {% if request.GET.order_by %}<input type="hidden" name="order_by" value="{{ request.GET.order_by }}">{% endif %}
                            {% if request.GET.ordering %}<input type="hidden" name="ordering" value="{{ request.GET.ordering }}">{% endif %}

                            <input type="submit" value="{% trans 'Search' %}" class="search-button">
                        </form>
                    </div>
                    <ul class="nav navbar-nav navbar-right user-nav">
                        {% if request.user.is_superuser %}
                            <li class="nav-link">
                                <a href="{% url 'admin:index' %}">
                                    <span class="icon material-symbols-outlined">admin_panel_settings</span>
                                    {% trans 'Admin' %}
                                </a>
                            </li>
                        {% endif %}
                        {% if request.user.is_authenticated %}
                            <li class="nav-link">
                                <a href="{% url 'user:account' %}">
                                    <span class="icon material-symbols-outlined">person</span>
                                    {% trans 'Account' %}
                                </a>
                            </li>
                            <li class="nav-link">
                                <a href="{% url 'account_logout' %}">
                                    <span class="icon material-symbols-outlined">logout</span>
                                    {% trans 'Log out' %}
                                </a>
                            </li>
                        {% else %}
                            <li class="nav-link">
                                <a href="{% url 'account_login' %}">
                                    <span class="icon material-symbols-outlined">login</span>
                                    {% trans 'Log in' %}
                                </a>
                            </li>
                            <li class="nav-link">
                                <a href="{% url 'account_signup' %}">
                                    <span class="icon material-symbols-outlined">app_registration</span>
                                    {% trans 'Register' %}
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

appstore/nextcloudappstore/core/templates/podcasts.html
{% load static %}

{# SPDX-FileCopyrightText: 2023 Nextcloud GmbH and Nextcloud contributors #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

<div class="podcast">
    <div class="podcast-details">
        <a href="{{ podcast.link }}" target="_blank">
            <h3>{{ podcast.title }}</h3>
        </a>
        <p>{{ podcast.excerpt }}</p>
    </div>
    <div class="podcast-image">
        <a href="{{ podcast.link }}" target="_blank">
            <img alt="Nextcloud Podcast" src="{{ podcast.image }}" title="Nextcloud Podcast">
        </a>
    </div>
</div>